name: Scrape web3.career every 12 hours
on:
  schedule:
    - cron: "5 */12 * * *"

jobs:
  scrape:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i firebase@latest
      - run: npm i
      - run: node src/scraping/web3.career/web3CareersScheduled.js
